### ISSUE TITLE
Просьба добавить информацию про возвраты 

### ISSUE THREAD

**Issue by xanf** [sinyakov/javascript-ninja#1]
Учитывая, что этот репозиторий начал использоваться как подтверждение "обмана" студентов, был бы благодарен, если бы для тех, кто предпочитает верить каждому першому, большими буквами написали, что все, кто запросил возврат за курс - его получили и что возврат можно получить до сих пор 

спасибо! и мира всем

**Comment by xanf** [comment]
если удобнее, могу открыть pr :)

**Comment by lavr-tsiporin** [comment]
> Учитывая, что этот репозиторий начал использоваться как подтверждение "обмана" студентов, был бы благодарен, если бы для тех, кто предпочитает верить каждому першому, большими буквами написали, что все, кто запросил возврат за курс - его получили и что возврат можно получить до сих пор
> 
> спасибо! и мира всем

Возможно эта информация соответствовала на 2019 год. На момент 4 мая 2022, Илья дает следующую информацию. С позволения Ильи, я не буду публиковать переписку, но выдерну сообщение из общего контекста группы. Надеюсь это не воспримется как "слив" информации в публичное поле, т.к. здесь отсутствует приватная информация.

**_Нет технической возможности вернуть. Возвраты на территорию РФ и РБ невозможны технически и сомнительны юридически, что касается возвратов на территорию другую - нет возможности финансовой, все ушло (все - это буквально все(ю) на поддержку зсу, тро и волонтеров_** 

Но справедливости ради, Илья не отказывается даже в этих условиях попытаться вернуть деньги.

**_Впрочем вы можете написать на почту [...] - как и всегда могли - я вам верну деньги [...] :) я всем всегда возвращал все. Буду ждать письма_**

PS. Информацию по курсу на дату 3 мая 2022 следующая:
**_Да, точно будет, точно - после войны, не точно - может и раньше, если вдруг война перейдет в затяжное ничего без официального окончания_**

**Comment by xanf** [comment]
@lavr-tsiporin у вас устаревшая уже опять информация :) всем все вернули, включая студентов на территории РФ (спасибо студентам из РФ)

**Comment by riyiro** [comment]
@xanf вы вернули деньги только тем, кто обратился. За два года многие могли забыть о курсе, сменить профессию или не захотеть требовать возврат по множеству причин. Получается, что часть людей так и не получила ни контента, ни компенсации, хотя заплатили за курс, да еще и потратили кучу времени на ожидания, ведь вы явно обещали, что контент будет.

**Comment by xanf** [comment]
@riyiro вы забываете, что первая часть была проведена и оплата была так же взята за половину. Равно как и про возврат регулярно напоминалось в чате. Поэтому тезис "ни контента ни компенсации" - я с ним не согласен.

Невыполненное обещание что контент будет - да, признаю.  Обещание данное 3 мая все ещё в силе
